import { CheckOutlined, EditOutlined, PauseOutlined, PlusOutlined, ReloadOutlined } from '@ant-design/icons'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { App, Button, Checkbox, Descriptions, Drawer, Empty, Form, Input, InputNumber, Modal, Select, Space, Table, Tag, Typography } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { useMemo, useState } from 'react'
import styled from 'styled-components'
import { getDictionaryItems } from '../../../services/dictionaryService'
import type { DictionaryItem } from '../../../types/dictionary'
import { confirmGovernanceMapping, createGovernanceMapping, createGovernanceMappingVersion, disableGovernanceMapping, getGovernanceMappings, getGovernanceStandards } from '../api'
import type { GovernanceAssetScope, GovernanceMappingRule, GovernanceMappingStatus } from '../types'

const Workspace = styled.section`min-width:0;`
const Header = styled.header`display:flex;align-items:flex-end;justify-content:space-between;gap:16px;margin-bottom:14px;@media(max-width:720px){align-items:stretch;flex-direction:column;}`
const ScopeGrid = styled.div`display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;@media(max-width:560px){grid-template-columns:1fr;}`

const statusMeta: Record<GovernanceMappingStatus, { label: string; color: string }> = {
  PENDING_CONFIRMATION: { label: '待确认', color: 'processing' }, CONFIRMED: { label: '已确认', color: 'success' }, DISABLED: { label: '已停用', color: 'default' },
}
const emptyScope: GovernanceAssetScope = { platform: '', productLine: '', base: '', productionLine: '', processSection: '', platformFamily: '', platformVariant: '' }

type FormValues = { standardId: number; sourceDimension: string; sourceValue: string; targetDictionaryItemId: number; scope: GovernanceAssetScope; ambiguous: boolean; affectedAssetCount: number; comment?: string }

export function GovernanceMappingsPage() {
  const { message } = App.useApp(); const client = useQueryClient(); const [selectedId, setSelectedId] = useState<number>(); const [drawer, setDrawer] = useState<'new' | 'version' | null>(null); const [confirming, setConfirming] = useState<GovernanceMappingRule | null>(null); const [filterStatus, setFilterStatus] = useState<GovernanceMappingStatus>(); const [queryText, setQueryText] = useState(''); const [form] = Form.useForm<FormValues>(); const [confirmForm] = Form.useForm<{ comment?: string }>()
  const mappings = useQuery({ queryKey: ['governance-mappings', filterStatus, queryText], queryFn: () => getGovernanceMappings({ status: filterStatus, query: queryText }) }); const standards = useQuery({ queryKey: ['governance-standards'], queryFn: getGovernanceStandards }); const dictionaries = useQuery({ queryKey: ['dictionary-items'], queryFn: getDictionaryItems })
  const selected = useMemo(() => mappings.data?.find(item => item.id === selectedId) ?? mappings.data?.[0], [mappings.data, selectedId])
  const refresh = () => client.invalidateQueries({ queryKey: ['governance-mappings'] })
  const save = useMutation({ mutationFn: (values: FormValues) => { const standard = standards.data?.find(item => item.id === values.standardId); if (!standard) throw new Error('请选择数据标准'); const input = { standardId: values.standardId, standardVersion: standard.standardVersion, sourceDimension: values.sourceDimension, sourceValue: values.sourceValue, targetDictionaryCategory: dictionaries.data?.find(item => item.id === values.targetDictionaryItemId)?.category ?? '', targetDictionaryItemId: values.targetDictionaryItemId, scope: values.scope, ambiguous: values.ambiguous, affectedAssetCount: values.affectedAssetCount }; return drawer === 'new' ? createGovernanceMapping(input) : createGovernanceMappingVersion(selected!.id, input) }, onSuccess: async result => { setDrawer(null); form.resetFields(); await refresh(); setSelectedId(result.id); void message.success('映射规则版本已新增') }, onError: error => void message.error(error instanceof Error ? error.message : '保存失败') })
  const confirm = useMutation({ mutationFn: (values: { comment?: string }) => confirmGovernanceMapping(confirming!.id, { version: confirming!.version, userId: 'demo-user', userName: '当前用户', comment: values.comment }), onSuccess: async () => { setConfirming(null); await refresh(); void message.success('映射规则已确认') }, onError: error => void message.error(error instanceof Error ? error.message : '确认失败') })
  const disable = useMutation({ mutationFn: () => disableGovernanceMapping(selected!.id, selected!.version), onSuccess: async () => { await refresh(); void message.success('映射规则已停用') }, onError: error => void message.error(error instanceof Error ? error.message : '停用失败') })
  const openEditor = (mode: 'new' | 'version') => { if (mode === 'version' && !selected) return; setDrawer(mode); form.setFieldsValue({ standardId: mode === 'version' ? selected!.standardId : standards.data?.find(item => item.status === 'ENABLED')?.id, sourceDimension: mode === 'version' ? selected!.sourceDimension : '', sourceValue: mode === 'version' ? selected!.sourceValue : '', targetDictionaryItemId: mode === 'version' ? selected!.targetDictionaryItemId : undefined, scope: mode === 'version' ? selected!.scope : emptyScope, ambiguous: mode === 'version' ? selected!.ambiguous : false, affectedAssetCount: mode === 'version' ? selected!.affectedAssetCount : 0 }) }
  const items = (dictionaries.data ?? []).filter(item => item.status === 'ENABLED')
  const columns: ColumnsType<GovernanceMappingRule> = [
    { title: '来源', key: 'source', width: 190, render: (_, row) => <Button type="link" style={{ padding: 0, textAlign: 'left' }} onClick={() => setSelectedId(row.id)}>{row.sourceDimension}：{row.sourceValue}</Button> },
    { title: '目标标准值', key: 'target', width: 150, render: (_, row) => <span>{row.targetName}<Typography.Text type="secondary">（{row.targetCode}）</Typography.Text></span> },
    { title: '范围', key: 'scope', width: 190, render: (_, row) => `${row.scope.platform} / ${row.scope.productLine} / ${row.scope.base}` },
    { title: '状态', dataIndex: 'status', width: 100, render: (status: GovernanceMappingStatus) => <Tag color={statusMeta[status].color}>{statusMeta[status].label}</Tag> },
    { title: '使用', dataIndex: 'usageCount', width: 70 }, { title: '命中', dataIndex: 'matchedAssetCount', width: 70 }, { title: '影响', dataIndex: 'affectedAssetCount', width: 70 },
    { title: '建议', key: 'auto', width: 110, render: (_, row) => row.status === 'CONFIRMED' && !row.ambiguous ? <Tag color="blue">可自动建议</Tag> : <Typography.Text type="secondary">需人工确认</Typography.Text> },
  ]
  return <Workspace><Header><div><Typography.Title level={3} style={{ margin: 0 }}>映射规则</Typography.Title><Typography.Text type="secondary">把历史来源值转换为受控标准值，确认后供自动建议使用</Typography.Text></div><Space wrap><Input.Search allowClear placeholder="搜索来源或目标" onSearch={setQueryText} style={{ width: 190 }} /><Select allowClear placeholder="筛选状态" value={filterStatus} onChange={setFilterStatus} options={Object.entries(statusMeta).map(([value, meta]) => ({ value, label: meta.label }))} style={{ width: 120 }} /><Button icon={<ReloadOutlined />} onClick={() => void refresh()}>刷新</Button><Button icon={<PlusOutlined />} type="primary" onClick={() => openEditor('new')}>新建规则</Button><Button icon={<EditOutlined />} disabled={!selected} onClick={() => openEditor('version')}>新增版本</Button></Space></Header>
    <Table rowKey="id" size="small" loading={mappings.isLoading} columns={columns} dataSource={mappings.data ?? []} onRow={row => ({ onClick: () => setSelectedId(row.id) })} scroll={{ x: 980 }} pagination={{ pageSize: 10, showSizeChanger: false }} locale={{ emptyText: <Empty description="暂无映射规则" /> }} />
    {selected && <Descriptions bordered size="small" column={{ xs: 1, sm: 2, md: 3 }} style={{ marginTop: 14 }} items={[{ key: 'standard', label: '数据标准', children: `${selected.standardCode} v${selected.standardVersion}` }, { key: 'rule', label: '规则版本', children: `v${selected.ruleVersion}` }, { key: 'confirm', label: '确认人', children: selected.confirmedByName ?? '尚未确认' }, { key: 'comment', label: '确认意见', children: selected.confirmationComment ?? '无' }, { key: 'scope', label: '完整适用范围', children: Object.values(selected.scope).join(' / ') }, { key: 'actions', label: '操作', children: <Space>{selected.status === 'PENDING_CONFIRMATION' && <Button size="small" icon={<CheckOutlined />} onClick={() => setConfirming(selected)}>确认</Button>}{selected.status === 'CONFIRMED' && <Button size="small" danger icon={<PauseOutlined />} onClick={() => Modal.confirm({ title: '停用该映射规则？', content: '停用后不会再用于自动建议。', onOk: () => disable.mutate() })}>停用</Button>}</Space> }]} />}
    <Drawer title={drawer === 'new' ? '新建映射规则' : '新增映射规则版本'} open={Boolean(drawer)} width={520} onClose={() => setDrawer(null)} destroyOnClose extra={<Button type="primary" loading={save.isPending} onClick={() => form.submit()}>保存</Button>}><Form form={form} layout="vertical" onFinish={values => save.mutate(values)}><Form.Item name="standardId" label="数据标准" rules={[{ required: true }]}><Select disabled={drawer === 'version'} options={(standards.data ?? []).filter(item => item.status !== 'DISABLED').map(item => ({ value: item.id, label: `${item.standardCode} v${item.standardVersion} · ${item.name}` }))} /></Form.Item><Form.Item name="sourceDimension" label="来源维度" rules={[{ required: true }]}><Input placeholder="例如：平台文本" /></Form.Item><Form.Item name="sourceValue" label="来源值" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="targetDictionaryItemId" label="目标字典项" rules={[{ required: true }]}><Select showSearch optionFilterProp="label" options={items.map((item: DictionaryItem) => ({ value: item.id, label: `${item.category} · ${item.name}（${item.code}）` }))} /></Form.Item><Typography.Text strong>完整适用范围</Typography.Text><ScopeGrid>{(['platform', 'platformFamily', 'platformVariant', 'productLine', 'base', 'productionLine', 'processSection'] as const).map(field => <Form.Item key={field} name={['scope', field]} label={{ platform: '平台', platformFamily: '平台族', platformVariant: '平台子类', productLine: '蓝本', base: '基地', productionLine: '拉线', processSection: '工序段' }[field]} rules={[{ required: true }]}><Input /></Form.Item>)}</ScopeGrid><Form.Item name="ambiguous" valuePropName="checked"><Checkbox>存在歧义，需要逐项业务确认</Checkbox></Form.Item><Form.Item name="affectedAssetCount" label="潜在影响数量" rules={[{ required: true }]}><InputNumber min={0} style={{ width: '100%' }} /></Form.Item></Form></Drawer>
    <Modal title="确认映射规则" open={Boolean(confirming)} onCancel={() => { setConfirming(null); confirmForm.resetFields() }} okText="确认" confirmLoading={confirm.isPending} onOk={() => confirmForm.submit()}><Form form={confirmForm} onFinish={values => confirm.mutate(values)}>{confirming?.ambiguous ? <Form.Item name="comment" rules={[{ required: true, message: '歧义规则必须填写业务确认意见' }]}><Input.TextArea rows={3} placeholder="填写业务确认意见" /></Form.Item> : <Typography.Text>该规则将进入可自动建议状态。</Typography.Text>}</Form></Modal>
  </Workspace>
}

export default GovernanceMappingsPage
